# ============================================
# 🤖 CodeRabbit AI Review + Production Readiness Scoring
# ============================================

review:
  enable: true
  on_pull_request: true
  on_push: false
  summary: true
  tone: "friendly senior engineer style"
  max_comments: 25

  reviewers:
    - name: "CodeRabbit AI"
      expertise:
        - "React"
        - "TypeScript"
        - "Supabase"
        - "TailwindCSS"
        - "Node.js"
        - "Security"

# --------------------------------------------
# 🧮 Readiness Scoring Configuration
# --------------------------------------------
readiness:
  enable: true
  scoring:
    code_quality: 0.30
    security_practices: 0.25
    performance: 0.20
    maintainability: 0.15
    documentation: 0.10

# --------------------------------------------
# 📜 Review Rules
# --------------------------------------------
rules:
  - name: Code Quality
    description: >
      Components must be modular, follow DRY, include error handling, and pass lint rules.

  - name: Security
    description: >
      No exposed keys; environment variables, Supabase RLS, and HTTPS must be used.

  - name: Performance
    description: >
      Optimize re-renders, imports, and use async/lazy loading where possible.

  - name: Maintainability
    description: >
      Consistent folder structure, reusable utils, and readable naming conventions.

  - name: Documentation
    description: >
      README.md, setup steps, and inline comments must be complete and current.

# --------------------------------------------
# 🔔 Optional Notifications
# --------------------------------------------
# Uncomment and configure if you want alerts when reviews are done:
#
# notifications:
#   slack:
#     enable: true
#     webhook_url: "https://hooks.slack.com/services/XXXX/XXXX/XXXX"
#     channel: "#code-reviews"
#   email:
#     enable: true
#     recipients:
#       - "youremail@example.com"
